version: '3.4'

services:
  jordiaragon.cinema.reservation:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "7172:80"
      - "7443:443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  azuresqledge.cinema:
    environment:
      - SA_PASSWORD=@someThingComplicated1234
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
    volumes:
      - ./containers/azuresqledge/:/var/opt/mssql

  eventstore.cinema:
    environment:
      - EVENTSTORE_INSECURE=true # let eventstore run without ceritficate
      - EVENTSTORE_EXT_TCP_PORT=1113 # set internal tcp port
      - EVENTSTORE_HTTP_PORT=2113 # set internal admin ui port
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - 2113:2113
      - 1113:1113
    volumes:
      - ./containers/eventstore/data/:/var/lib/eventstore
      - ./containers/eventstore/logs/:/var/log/eventstore

  rabbitmq.cinema:
    ports:
        - 5672:5672
        - 15672:15672
    #volumes: 
        #- ./containers/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
        #- ./containers/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json