version: '3.4'

services:
  jordiaragonzaragoza.cinema.reservation:
    image: ${DOCKER_REGISTRY-}jordiaragonzaragoza.cinema.reservation
    container_name: jordiaragonzaragoza.cinema.reservation
    build:
      context: .
      dockerfile: src/JordiAragonZaragoza.Cinema.Reservation/Dockerfile

  postgres.cinema:
    image: postgres:15.1-alpine
    container_name: postgres.cinema
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "wal_compression=on"

  pgadmin.cinema:
    image: dpage/pgadmin4
    container_name: pgadmin.cinema

  eventstore.cinema:
    image: eventstore/eventstore:23.10.1-alpha-arm64v8
    # use this image if you're running on x86 proc
    # image: eventstore/eventstore:23.10.1-bookworm-slim
    container_name: eventstore.cinema

  rabbitmq.cinema:
    image: rabbitmq:3.11.10-management
    container_name: rabbitmq.cinema
    hostname: rabbitmq

  redis.cinema:
    image: redis:7.2.5-alpine
    container_name: redis.cinema