version: '3.4'

services:
  jordiaragon.cinema.reservation:
    image: ${DOCKER_REGISTRY-}jordiaragon.cinema.reservation
    container_name: jordiaragon.cinema.reservation
    build:
      context: .
      dockerfile: src/JordiAragon.Cinema.Reservation/Dockerfile
    depends_on:
      - "azuresqledge.cinema"
      - "eventstore.cinema"
      - "rabbitmq.cinema"
    links:
      - "azuresqledge.cinema"
      - "eventstore.cinema"
      - "rabbitmq.cinema"

  azuresqledge.cinema:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: azuresqledge.cinema

  eventstore.cinema:
    image: eventstore/eventstore:23.10.1-alpha-arm64v8
    container_name: eventstore.cinema

  rabbitmq.cinema:
    image: rabbitmq:3.11.10-management
    container_name: rabbitmq.cinema
    hostname: rabbitmq