version: '3.4'

networks:
  cinema-network:
    driver: bridge

services:
  jordiaragonzaragoza.cinema.reservation:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - 5001:80
      - 7001:443
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    networks:
      - cinema-network

  postgres.cinema:
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - ./containers/postgres/data:/var/lib/postgresql/data
      #- ./containers/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cinema-network

  pgadmin.cinema:
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-postgres}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"
    user: root
    volumes:
      - ./containers/pgAdmin/pgpass:/pgpass
      - ./containers/pgAdmin/servers.json:/pgadmin4/servers.json
    restart: unless-stopped
    networks:
      - cinema-network

  eventstore.cinema:
    user: root
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113 # set internal tcp port
      - EVENTSTORE_HTTP_PORT=2113 # set internal admin ui port
      - EVENTSTORE_INSECURE=true # let eventstore run without certificate
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - 2113:2113
      - 1113:1113
    volumes:
      - ./containers/eventstore/data/:/var/lib/eventstore
      - ./containers/eventstore/logs/:/var/log/eventstore
    networks:
      - cinema-network

  rabbitmq.cinema:
    ports:
        - 5672:5672
        - 15672:15672
    #volumes: 
        #- ./containers/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
        #- ./containers/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    networks:
      - cinema-network

  redis.cinema:
    ports:
        - 6379:6379
    restart: always
    networks:
      - cinema-network