version: '3.4'

services:
  jordiaragon.cinemas.reservation:
    image: ${DOCKER_REGISTRY-}jordiaragon.cinemas.reservation
    container_name: jordiaragon.cinemas.reservation
    build:
      context: .
      dockerfile: src/JordiAragon.Cinemas.Reservation/Dockerfile
    depends_on:
      - "azuresqledge.cinemas"
      - "eventstore.cinemas"
      - "rabbitmq.cinemas"
    links:
      - "azuresqledge.cinemas"
      - "eventstore.cinemas"
      - "rabbitmq.cinemas"

  azuresqledge.cinemas:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: azuresqledge.cinemas

  eventstore.cinemas:
    image: eventstore/eventstore:22.10.2-alpha-arm64v8
    container_name: eventstore.cinemas

  rabbitmq.cinemas:
    image: rabbitmq:3.11.10-management
    container_name: rabbitmq.cinemas
    hostname: rabbitmq